apiVersion: apps/v1
kind: Deployment
metadata:
  name: reference-service-go
  namespace: reference-service-showcase
  labels:
    app.kubernetes.io/name: reference-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: reference-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: reference-service
    spec:
      containers:
        - name: reference-service-go
          image: nzacharia/reference-service-go-pub
          imagePullPolicy: Never
          ports:
            - containerPort: 8080